name: app_to_do_list
description: A new Flutter project.

# Se deseja publicar no pub.dev, remova a linha abaixo
publish_to: 'none'

# Versão do aplicativo
version: 1.0.0+1

# Configurações do ambiente Flutter/Dart
environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5   # Versão atualizada do provider
  cupertino_icons: ^1.0.8
  intl: ^0.18.0      # Adicionando o pacote intl para formatação de datas

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  # Definição de ativos (imagens, etc.)
  assets:
    - assets/user.png
